"""incluindo colunas na tabela integrantes

Revision ID: 081464269fea
Revises: 5d884d5d20cc
Create Date: 2021-04-21 00:55:19.555422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081464269fea'
down_revision = '5d884d5d20cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrantes', sa.Column('projeto', sa.String(), nullable=True))
    op.add_column('integrantes', sa.Column('usuario', sa.String(), nullable=True))
    op.create_foreign_key(None, 'integrantes', 'usuarios', ['usuario'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'integrantes', 'projetos', ['projeto'], ['nome'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integrantes', type_='foreignkey')
    op.drop_constraint(None, 'integrantes', type_='foreignkey')
    op.drop_column('integrantes', 'usuario')
    op.drop_column('integrantes', 'projeto')
    # ### end Alembic commands ###
