"""token.name set unique to TRUE

Revision ID: 42f7e9055404
Revises: fae68409505d
Create Date: 2021-04-20 03:02:36.445265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f7e9055404'
down_revision = 'fae68409505d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('solicitante', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante'], ['token.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('token', sa.Column('token', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'token', ['token'])
    op.create_unique_constraint(None, 'token', ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_column('token', 'token')
    op.drop_table('solicitacoes')
    # ### end Alembic commands ###
