"""criando tabela solicitacoes

Revision ID: 5d091150ee4d
Revises: f18e1920e4f5
Create Date: 2021-04-20 03:14:06.887731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d091150ee4d'
down_revision = 'f18e1920e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('solicitante', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante'], ['token.user'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('solicitacoes')
    # ### end Alembic commands ###
