"""adicionando coluna na tabela de solicitações: coluna: email

Revision ID: 5d884d5d20cc
Revises: 888410d9c909
Create Date: 2021-04-20 13:49:16.387697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d884d5d20cc'
down_revision = '888410d9c909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes', sa.Column('user_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'solicitacoes', 'usuarios', ['user_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    op.drop_column('solicitacoes', 'user_email')
    # ### end Alembic commands ###
