"""adicionando colunas na tabela de integrantes

Revision ID: 86264b721b0d
Revises: b4c08f8f4650
Create Date: 2021-04-21 01:01:42.724399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86264b721b0d'
down_revision = 'b4c08f8f4650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('projeto', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.email'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrantes')
    # ### end Alembic commands ###
