"""alterando solicitacoes model solicitante para id ao invés de email

Revision ID: 888410d9c909
Revises: 9085b63a8f38
Create Date: 2021-04-20 13:00:32.387186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888410d9c909'
down_revision = '9085b63a8f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes', sa.Column('solicitante', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitacoes', 'token', ['solicitante'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    op.drop_column('solicitacoes', 'solicitante')
    # ### end Alembic commands ###
