"""adicionando coluna na tabela projetos

Revision ID: ac2e386aef0d
Revises: 2c1f48dfecb6
Create Date: 2021-04-20 02:11:24.778739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2e386aef0d'
down_revision = '2c1f48dfecb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projetos', 'usuarios', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'owner_id')
    # ### end Alembic commands ###
