"""adicionando colunas na tabela de integrantes

Revision ID: b4c08f8f4650
Revises: 081464269fea
Create Date: 2021-04-21 00:59:28.675881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c08f8f4650'
down_revision = '081464269fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrantes', sa.Column('projeto', sa.String(), nullable=False))
    op.add_column('integrantes', sa.Column('usuario', sa.String(), nullable=True))
    op.create_foreign_key(None, 'integrantes', 'usuarios', ['usuario'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integrantes', type_='foreignkey')
    op.drop_column('integrantes', 'usuario')
    op.drop_column('integrantes', 'projeto')
    # ### end Alembic commands ###
