"""alterando solicitacoes model solicitante para id ao invés de email

Revision ID: bae36845777a
Revises: 5da00f787ba4
Create Date: 2021-04-20 12:55:39.323951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae36845777a'
down_revision = '5da00f787ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'solicitacoes', 'token', ['solicitante'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    # ### end Alembic commands ###
