"""alterando coluna user de token para not unique

Revision ID: dbd7ea463b7f
Revises: 5d091150ee4d
Create Date: 2021-04-20 12:46:10.525257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd7ea463b7f'
down_revision = '5d091150ee4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_user_key', 'token', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('token_user_key', 'token', ['user'])
    # ### end Alembic commands ###
